### PR TITLE
Cmd line flag `-c` for config location

### PR DESCRIPTION
**Pull request by stblassitude**
Add command line parsing and a flag `-c` to specify where the config
file should be loaded from.

### CODE REVIEW

**Comment by Ajedi32** [comment]
Fixes #96

**Review by joohoi — CHANGES_REQUESTED** [review]
Thanks for the PR! It looks good, I only have a single concern here;

The default value is `./config.cfg`, making it always being set pretty much. Previously `acme-dns` defaulted to checking if `/etc/acme-dns/config.cfg` existed, and only after then `./config.cfg`. In hindsight this was a unintuitive and borderline stupid move. However I think that we need to keep the previous default behavior, as that's what people currently running the software have become to expect.

This being the fact, I'm asking if we could change the default value to an empty string, checking if the string is set, and only then overriding the old behavior.

**Comment by stblassitude** [comment]
I've updated the PR: if specified, the arguments' path is used, otherwise /etc/acme-dns/config.cfg, finally ./config.cfg.

**Review by joohoi — APPROVED** [review]

**Comment by joohoi** [comment]
LGTM! Thanks for working on this!

**Pull request merged**
