### PR TITLE
Add the possibility to manage multiple domains automatically

### PR DESCRIPTION
**Pull request by wdoekes**
By setting the ``records`` subdomain to ``*`` you allow the account to
autoregister new subdomains.

Use ``_acme-challenge.example.com CNAME example.com.your-challenge.tld``
CNAMEs on all domains you wish to manage letsencrypt certificates for.

----

Hi Joona, I don't expect you to merge this verbatim, but I thought I'd let you know how I changed some stuff around for usability over here.

Thanks for the work!

Feel free to close this PR.

### CODE REVIEW

**Comment by wdoekes** [comment]
Closing so you're not bothered by our branch updates. I might come back later if our changes have stabilized. Thanks again!

**Comment by joohoi** [comment]
Thanks for the headsup! Looks interesting, feel free to ping me when you reach different milestones here.

**Comment by wdoekes** [comment]
@joohoi : done for now.

- I fixed/added the tests. As far as I know, it's still compatible with upstream.
- I added our modified version of your certbot hook; which is not compatible with yours.
- I don't see any need right now to make registration of custom (sub)domains easier than by hand-hacking DB records.

If you want a PR of (parts) of our changes, let me know, and I'll gladly create one.

**Comment by andrewda** [comment]
Hi @wdoekes! It's been a few years, but I've got a similar use case and was wondering what the current status of this is. Have you used this in production at all? If there's anything else you know needs to be changed or looked into further, I'd be happy to take over!

@joohoi, is this something you'd still be interested in having as an optional feature in `acme-dns`?

**Comment by wdoekes** [comment]
Hi @andrewda,

we've been using https://github.com/ossobv/acme-dns/commits/ossobv-readable-subdomains in production since it was made (ossobv/acme-dns:v0.7.2-13-gd2261e5-ossobv on docker).

Right now you have to hand-hack the records table after you register a new account, like the README already mentions. But we don't create new accounts daily (especially not the super-domain account):
https://github.com/ossobv/acme-dns/commit/ff92ba0b1dfd2cee194f10c9733250bea77d432a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R25-R26

(Additionally, we're using additional security on the ingresss to the acme-dns HTTP API. So we don't get any robots other than our own trying to `/register` or '/update'.)

(Sub)domain matching done in the acme-dns-client:
https://github.com/ossobv/acme-dns/blob/d2261e5173dd814845224d0577af5fdfef859ae2/acme-dns-auth-ossobv.py#L76-L93
https://github.com/ossobv/acme-dns/blob/d2261e5173dd814845224d0577af5fdfef859ae2/acme-dns-auth-ossobv.py#L98-L100

Good luck.

**Pull request closed without merging**
