### PR TITLE
Add Windows ACME Simple (win-acme) to clients list

### PR DESCRIPTION
**Pull request by Daniel15**
win-acme is probably the easiest open-source client to use on Windows, and as of the latest alpha it supports acme-dns 😃

### CODE REVIEW

**Comment by joohoi** [comment]
Thanks for the PR! I would prefer to add it when it's got a non-alpha release supporting `acme-dns`. Would it be possible to modify the PR to remove the version info, and we'll merge when it's released? They seem to have a pretty active release cycle, so it shouldn't take too long!

**Comment by Daniel15** [comment]
Sure, will wait until the stable release 😄

**Comment by WouterTinus** [comment]
I've just released a stable version with acme-dns support, so feel free to merge when convenient!

**Comment by joohoi** [comment]
Awesome, thanks for the update!

**Pull request merged**
