### PR TITLE
Add information about running with non-elevated permisions

### PR DESCRIPTION
**Pull request by Daniel15**
Explain `CAP_NET_BIND_SERVICE` capability, and iptables.

### CODE REVIEW

**Comment by joohoi** [comment]
Thanks for the PR! This looks awesome, and I was actually unaware of the capabilities system. Unfortunately I have issues veryfying this behavior, as can be seen below. I wonder if I'm testing it wrong somehow?

This is on Debian Stretch running 4.9.82-1+deb9u3 kernel.
```
go/src/acme-dns  master ✔                                                                   
▶ sudo setcap 'cap_net_bind_service=+ep' ./acme-dns

go/src/acme-dns  master ✔                                                                   
▶ ./acme-dns 
INFO[0000] Using config file                             file=/etc/acme-dns/config.cfg
DEBU[0000] Adding new record type to domain              domain=auth.example.org. recordtype=A
DEBU[0000] Adding new record type to domain              domain=ns1.auth.example.org. recordtype=A
DEBU[0000] Adding new record type to domain              domain=ns2.auth.example.org. recordtype=A
DEBU[0000] Adding new record type to domain              domain=auth.example.org. recordtype=NS
DEBU[0000] Adding new record type to domain              domain=auth.example.org. recordtype=NS
DEBU[0000] Adding new record type to domain              domain=cname.auth.example.org. recordtype=CNAME
DEBU[0000] Adding new record type to domain              domain=auth.example.org. recordtype=SOA
INFO[0000] Connected to database                        
INFO[0000] Listening HTTP                                host="0.0.0.0:80"
FATA[0000] listen tcp 0.0.0.0:80: bind: permission denied 

go/src/acme-dns  master ✔                                                                
▶ getcap ./acme-dns
./acme-dns = cap_net_bind_service+ep
```
And strace reports: 
```
[pid 11362] bind(5, {sa_family=AF_INET6, sin6_port=htons(80), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28 <unfinished ...>
[pid 11364] <... pselect6 resumed> )    = 0 (Timeout)
[pid 11362] <... bind resumed> )        = -1 EACCES (Permission denied)
```

**Comment by Daniel15** [comment]
Hmm, that's strange! It definitely works for me on Debian buster (testing) running kernel 4.14.17-1. I'm starting acme-dns using systemd, but it works fine if I just run it directly too. I'm running it as a user named "dns"

**Comment by joohoi** [comment]
I'll try to dig into this tomorrow to find out if it's something in my system, and/or if we need to expand the information to be added about capabilities.

**Comment by Daniel15** [comment]
I just finished fully setting mine up, you can look up `_acme-challenge.dl.vc` to see it in action:

```
daniel@DANLO--155:~$ dig TXT _acme-challenge.dl.vc

; <<>> DiG 9.10.3-P4-Ubuntu <<>> TXT _acme-challenge.dl.vc
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10518
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_acme-challenge.dl.vc.         IN      TXT

;; ANSWER SECTION:
_acme-challenge.dl.vc.  3600    IN      CNAME   1c5de30a-7040-47f0-837f-b70fa189a74c.acme.d.sb.
1c5de30a-7040-47f0-837f-b70fa189a74c.acme.d.sb. 1 IN TXT "Gvk9xSIlKJ4rYWh_9yyF170abPUqf5mQiMINfAyKaes"
1c5de30a-7040-47f0-837f-b70fa189a74c.acme.d.sb. 1 IN TXT "4mvKEK_2t6DXV6Vc7Xx_vvdvoN2O4W60r1YfS-tpIIk"

;; Query time: 323 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Sun Mar 18 16:10:46 DST 2018
;; MSG SIZE  rcvd: 222
```

So listening on port 53 is working fine, and I've confirmed it's running as the unprivileged "dns" user:
```
16:13 daniel@vps03 /home/daniel
% ps aux | grep acme
daniel   11137  0.0  0.0  12904   976 pts/5    S+   16:13   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn acme
dns      26872  0.0  0.2 392156 11252 ?        Ssl  15:24   0:00 /home/dns/go/bin/acme-dns

```

**Comment by joohoi** [comment]
Ok, I was able to figure this out. Apparently, though undocumented, mount options did play a role here. The path I was running acme-dns from, was mounted with options `nodev, nosuid`. I suspect that `nosuid` was the issue here. I was able to solve the issue by moving the executable to a different file path.

That said, I think we should prepend the suggestion to use capabilities with something like "You may also have luck with"... or something alike, pointing out that there might be factors that limit the usability.

**Comment by Daniel15** [comment]
Makes sense! I'll update the PR soon.

**Comment by gabe565** [comment]
Another thing to note here is that these capabilities can also be added through systemd  as a directive in the `[Service]` block like this:
```ini
AmbientCapabilities=CAP_NET_BIND_SERVICE
```

I had to do it this way since apparently some servers (distros? Not sure if it is environment-specific) do not have the `setcap` command included with the `libcap2-bin` package.

On another note, can anybody get `authbind` working with `acme-dns`? I could not get it to work. It would just not bind and not notify me (Although this is partially a problem with #70 which is already documented)

**Comment by joohoi** [comment]
> Another thing to note here is that these capabilities can also be added through systemd as a directive in the [Service] block like this:

Nice! I wasn't aware of this. Is it universally supported?

About the authbind; haven't tried using it. I believe we should pick one approach and recommend that, and setting capabilities from systemd service unit sounds like awesome candidate for this.

**Comment by gabe565** [comment]
> Nice! I wasn't aware of this. Is it universally supported?

The capabilities (like `CAP_NET_BIND_SERVICE`) has been in Linux kernel for quite a while (`capabilities` man page says since Linux 2.2) and any system with systemd should have the option available as long as they are running acme-dns as a systemd service.

> About the authbind; haven't tried using it.

I like that authbind only allows a certain user to bind to specific ports instead of allowing _any_. It even has a `--deep` flag where it is tries to allow binding on spawned children, but it doesn't seem to work with the DNS library that `acme-dns` is using for some reason. strace just shows Permission Denied errors.

> I believe we should pick one approach and recommend that, and setting capabilities from systemd service unit sounds like awesome candidate for this.

Yeah might as well go ahead and recommend the systemd service which adds the bind capability.     
I could provide the systemd service that I am using now if it helps, just let me know!

**Comment by Daniel15** [comment]
> Another thing to note here is that these capabilities can also be added through systemd as a directive in the [Service] block like this

Oh wow, that's awesome! I think that's a better idea than just granting the capability to the executable. Would you like to send a PR to add that to the docs? In that case I'll close this PR.

**Comment by gabe565** [comment]
> Oh wow, that's awesome! I think that's a better idea than just granting the capability to the executable.

I mean it still does the same thing in the end, just using a systemd directive allows it to be added to a service which loads at boot.

> Would you like to send a PR to add that to the docs?

I think we should keep your text, but add a bit about running acme-dns as a systemd service afterwards. I can add onto it!

**Comment by Daniel15** [comment]
> just using a systemd directive allows it to be added to a service which loads at boot.

Config in a file is much better than some random invisible capability flag somewhere. I'm still not sure if upgrading an app (replacing its executable with a new version) removes its old capabilities, for example. With something configured in the systemd config, I can just restore it from backup to a new server and it'll work, without me having to remember I need to set a capability flag.

**Comment by gabe565** [comment]
> Config in a file is much better than some random invisible capability flag somewhere.

Since my servers do not have the `setcap` command, I didn't even look much into how it worked. In my head it ran the executable with that capability, but you are definitely right about the flags. Way too easy to forget about and cause headache later on.

I created a PR #83 adding systemd information with a service file, but I still think these could both be pulled in with yours being listed as a fallback. Not all systems have systemd yet!

**Comment by joohoi** [comment]
With #83 landed, and we seem to have consensus that it is the right approach, I'm closing this. Feel free to comment here if this was not the case, and I'll reopen.

**Pull request closed without merging**
