### PR TITLE
simplify example dns config

### PR DESCRIPTION
**Pull request by Yannik**

### CODE REVIEW

**Comment by Yannik** [comment]
I would very much like to simply the example config, as the current one is overly complicated. I hope this is okay with you.

**Comment by joohoi** [comment]
Thanks for the PR! Sorry for keeping it sitting in the PR queue for too long. This makes it much easier to grok and handle.

**Comment by Yannik** [comment]
@joohoi Uhm, I think something went wrong here. You merged the acme-dns master branch into my fork instead of the other way around :-)

**Comment by joohoi** [comment]
It's one of the GitHub features that brings the PR branch up to speed with master (if master was updated in between) in order to merge it in later :)

**Comment by joohoi** [comment]
I'm waiting for the tests to pass to be able to merge this.

**Comment by joohoi** [comment]
Aand here we go, thanks again!

**Comment by Yannik** [comment]
@joohoi Now that I'm reviewing this patch, it seems odd to me that you were using `auth.example.com` on lines 178/179 and `auth.example.org` in the example config? 
Also the IPs on line 178 and in the config differ.

Was there a reason for this I just cannot recall?

**Comment by joohoi** [comment]
The inconsistencies were because I failed to review PR #64 correctly, matching with the rest of the README.md context. These probably should be matched, do you want to do it or should I?

**Comment by Yannik** [comment]
@joohoi I'll provide a PR for this

**Comment by Ajedi32** [comment]
FYI, this change may be causing problems. See https://github.com/joohoi/acme-dns/issues/119#issuecomment-427867434

> The problem I ran into is that the documentation was a little confusing for me since the name of the DNS subdomain, and the name of the DNS nameserver are identical and it's never mentioned that auth.example.com is the NS or the subdomain we're authorizing for. My DNS provider (dnsmadeeasy) doesn't allow the nameserver to have the same name as the subdomain.

**Comment by Yannik** [comment]
@Ajedi32 You do not need to set both a NS record and A/CNAME record at your provider. The A/CNAME is ignored anyway, as it is resolved by your own NS.

Have a look at this `dig` trace:
```
[yannik@yannik-laptop ~]$ dig +trace acme-dns.mydomain.org
--snip resolve .org tld --

mydomain.org.		86400	IN	NS	ns1.provider.net.
mydomain.org.		86400	IN	NS	ns2.provider.net.
mydomain.org.		86400	IN	NS	ns3.provider.net.
;; Received 610 bytes from 199.249.112.1#53(a2.org.afilias-nst.info) in 55 ms

acme-dns.mydomain.org. 60	IN	NS	mydomain.org.
;; Received 82 bytes from 194.50.113.2#53(ns2.provider.net) in 71 ms

acme-dns.mydomain.org. 3600	IN	CNAME	mydomain.org.
;; Received 92 bytes from 5.45.101.249#53(mydomain.org) in 74 ms
```

**Pull request merged**
