### PR TITLE
Added Posh-ACME to client list

### PR DESCRIPTION
**Pull request by rmbolger**
I just merged the first version of the acme-dns plugin for Posh-ACME via rmbolger/Posh-ACME#4. So it's in the master branch, but I'm hoping to get a few more plugins written before making a new official release. I understand if you want to wait to accept this PR until that happens.

### CODE REVIEW

**Comment by joohoi** [comment]
If you feel that it's ready, we can add it. I would prefer the client list to be in alphabetical order however.

**Comment by rmbolger** [comment]
It's definitely working. But it's probably best to wait for the release so that people getting the client through the normal PowerShell Gallery channel will have the plugin.

**Comment by joohoi** [comment]
Ok, sounds good. LMK when it's ready.

**Review by joohoi — APPROVED** [review]

**Comment by rmbolger** [comment]
Posh-ACME 1.1 is now released to the PowerShell Gallery and contains acme-dns support. All good to merge this.

**Comment by joohoi** [comment]
Nice! Merged

**Pull request merged**
