### PR TITLE
Added http health check endpoint.

### PR DESCRIPTION
**Pull request by Kugelschieber**
Added:

* GET endpoint on /health to check if the server is up and running
* unit test for it
* documentation in readme
* added .idea/ to .gitignore (to ignore GoLand IDE settings)

### CODE REVIEW

**Comment by Kugelschieber** [comment]
My test passed, but TestUpdateAllowedFromIP failed. Any idea why?

**Comment by joohoi** [comment]
Ok, so there was a bug in the failing test. The previous order that the tests were run ensured that the failing test had a non-default state for `Config` struct. This is fixed in #139 which I'll merge ASAP. That should fix this issue.

For the scope of this PR, it looks great! Thanks! The only modification I'd like to see would be ensuring returning HTTP status `200`, as the default behavior of the underlying framework might change in the future. I'm thinking something simple along the lines of:
```
// Endpoint used to check the readiness and/or liveness (health) of the server.
func healthCheck(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
	// does nothing except returning status code 200 (which it does by default)
	w.WriteHeader(http.StatusOK)
}
```

**Comment by Kugelschieber** [comment]
Like this?
```
## Changelog


- master
   - Unreleased
      - Added new endpoint to perform health checks
   - Changed
      - A new protocol selection for DNS server "both", that binds both - UDP and TCP ports.
- v0.6
```

**Comment by joohoi** [comment]
Thanks for your work! LGTM, and merging when the test runs finish!

**Pull request merged**
