### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by fritterhoff**
Hi,

several dependencies are a bit outdated so I've updated them (including the changes for #220 ). According to my tests nothing should be broken afterwards 😉

### CODE REVIEW

**Comment by fritterhoff** [comment]
Hi @joohoi,

is the project still maintained? 

Thanks :)

**Comment by joohoi** [comment]
Hi, It is. I have just been really busy lately! Thanks for the PR, I'll look into it within a few days.

**Comment by fritterhoff** [comment]
Hi, @joohoi do you have any update for me? 😀

**Comment by fritterhoff** [comment]
Hello? :) 
Do you need any further information/tests/... ? 
Thanks 👍🏼

**Comment by ZPascal** [comment]
Hi @joohoi could you please check the PR? I think it makes sense to update the Golang version (if possible). @fritterhoff I think in the meantime, it could make sense to update to version 1.17 directly, what do you think?

**Comment by fritterhoff** [comment]
Sure - it makes more sense to use an up-to-date version, but without any feedback/reaction it is a pity to waste any time 😞

**Comment by fritterhoff** [comment]
@ZPascal I've updated the dependencies and the base image to 1.17 a few days ago.

**Pull request closed without merging**
